---
name: | 
  José Daniel Conejeros
date: 'Abril 2020'
position: | 
  | [Magíster(c) en Sociología](http://sociologia.uc.cl/postgrado/magister-en-sociologia/), Pontificia Universidad Católica de Chile
  | Licenciado en Ciencias Sociales, Pontificia Universidad Católica de Chile
address: Santiago, Chile. Abril 2020
#profilepic: JConejeros.jpg
phone: +56 9 64924057
email: jdconejeros@uc.cl
aboutme: | 
  | Temas de interés: pobreza, desigualdad, justicia social, ciencia de datos y metodologías cuantitativas. 
  | Autodidacta en la programación para el procesamiento, análisis y visualización de datos sociales. 
linkedin: joseconejerosp
github: JDConejeros
headcolor: 203C60
output: 
  vitae::awesomecv:
    keep_tex: true
header-includes:
- \geometry{left=1.4cm, top=1.5cm, right=1.4cm, bottom=1.8cm, footskip=.5cm}
- \setbool{acvSectionColorHighlight}{false}
- \definecolor{darktext}{HTML}{182D47} #Secciones
- \definecolor{text}{HTML}{595959} #Texto
- \definecolor{graytext}{HTML}{101E2F} #Títulos
- \definecolor{lighttext}{HTML}{808080} # Pie de página
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

```{r get data, include=FALSE}
library(here)
library(glue)

## Education
edu <- read_csv2(here::here("data", "education.csv"))
edu2 <- read_csv2(here::here("data", "education2.csv"))

## Research Experience 
jobs1 <- read_csv2(here::here("data", "jobs1.csv"))

## Consulting Experience 
jobs2 <- read_csv2(here::here("data", "jobs2.csv"))

## Training
training <- read_csv2(here::here("data", "training.csv"))

## Teaching 
teaching1 <- read_csv2(here::here("data", "teaching1.csv"))
teaching2 <- read_csv2(here::here("data", "teaching2.csv"))

## Skils
skills <- read_csv2(here::here("data", "skills.csv")) %>% 
  group_by(category) %>% 
  mutate(skill = paste(skill, collapse = " - ")) %>% 
  ungroup %>% 
  unique

## Grants
grants <- read_csv2(here::here("data", "grants.csv"))

## Presentations
presentations <- read_csv2(here::here("data", "presentations.csv"))
```

# Educación 

```{r}
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni,
                 why = details)
```

# Experiencia en investigación

```{r}
jobs1 %>% 
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = company,
    where = where,
    why = details)
```


# Experiencia profesional

```{r}
jobs2 %>% 
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = company,
    where = where,
    why = details)
```

# Experiencia en Docencia

\footnotesize{
Ayudante y colaborador de docencia a nivel universitario en cursos a nivel teórico y metodológico.   
}

```{r}
teaching1 %>% 
  detailed_entries(
    what = what, 
    when = when,
    with = with, 
    where = where, 
    why = why)
```

```{r}
teaching2 %>% 
  detailed_entries(
    what = what, 
    when = when, 
    with = with, 
    where = where, 
    why = why)
```


# Cursos 

```{r}
training %>% 
  detailed_entries(
    what = what, 
    with = with, 
    when = when, 
    where = where, 
    why = why)
```

\break

# Habilidades

```{r}
skills %>% 
  detailed_entries(
    why = skill, 
    what = category)
```


# Presentaciones 

```{r}
presentations %>% 
  detailed_entries(
    what = what,
    with = with,
    when = when,
    where = where,
    why = why)
```

# Becas y Premios

```{r}
grants %>% 
  detailed_entries(
    what = what, 
    with = with, 
    when = when,  
    where = where)
```

# Otros antecedentes 

```{r}
detailed_entries(edu2, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni,
                 why = details)
```
